### ISSUE TITLE
TypeError: this.listener is not a function

### ISSUE THREAD

**Issue by kevinfoerster** [taming-the-state-in-react/gatsby-firebase-authentication#37]
Hi,

i just installed this project on node v8.10.0 and updated the credentials in src/components/Firebase/firebase.js.

i am getting an this error whenever i click a link…
```
TypeError: this.listener is not a function
```

any idea why this happens?

**Comment by rwieruch** [comment]
Hi @kevinfoerster Thanks for noticing this issue. Can you pull the latest changes or clone the repository again? I think I have fixed the issue with the latest commit. Let me know if it works for you.

**Comment by kshep425** [comment]
Hi,

@rwieruch I had the same issue clicking a link to open a new page yesterday.  I worked around it by checking the type first because it is returning a promise instead of a function on the withAuthorization and withAuthentication files on componentWillUnmount.

      if(typeof this.listener === "function"){
        this.listener();
      }

But I am new to this, and it could also be that I am not wrapping the link correctly.
