### ISSUE TITLE
Firebase App named '[DEFAULT]' already exists (app/duplicate-app)

### ISSUE THREAD

**Issue by zlydenko** [taming-the-state-in-react/gatsby-firebase-authentication#40]
![image](https://user-images.githubusercontent.com/35955866/53348482-cac41f00-3923-11e9-9ae3-2bb6567e919c.png)

**Comment by razvan-soare** [comment]
Hey @zlydenko make sure you add the .env file with your firebase settings

gatsbys default env file is -> .env.development and .env.production (if i remember good) 

then go to firebase console and search for `Add Firebase to your web app` and you will get all the settings and keys there.

```
REACT_APP_API_KEY = '#######'
REACT_APP_AUTH_DOMAIN = '#######'
REACT_APP_DATABASE_URL = '######'
REACT_APP_PROJECT_ID = '######'
REACT_APP_STORAGE_BUCKET = '######'
REACT_APP_MESSAGING_SENDER_ID = '#######'
REACT_APP_CONFIRMATION_EMAIL_REDIRECT = 'YOUR_URL'
```

**Comment by dandv** [comment]
I had the same error because I followed [the instructions](https://github.com/the-road-to-react-with-firebase/react-gatsby-firebase-authentication#firebase-configuration) and chose the second option, to name the file `.env`. After I renamed it `.env.development`, the error was fixed. I'm just getting started with Gatsby, so I'm not sure if `.env` doesn't work, but in that case, the instructions should be changed to remove that second option.
